#!/bin/bash

ROOT_DIR=$(pwd)
# source test helpers
cd "$(dirname "${BASH_SOURCE[0]}")" && source "utils.sh"
# go back to original directory
cd "${ROOT_DIR}"

EXIT_CODE=0

# main entry point
if [ "$(get_os)" == "macos" ]; then
    ./install macos || EXIT_CODE=1

    # rvm
    rvm get stable

    # path
    export PATH=/usr/local/bin:$PATH

    # brew
    # uninstall preinstalled packages on Travis
    # https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/
    brew remove --force $(brew list) --ignore-dependencies
    brew cleanup

    brew update
    brew linkapps
    brew bundle || EXIT_CODE=1
elif [ "$(get_os)" == "ubuntu" ]; then
    ./install linux || EXIT_CODE=1
elif [ "$(get_os)" == "windows" ]; then
    echo "Windows has no tests"

    EXIT_CODE=1
else
    echo "[ERROR]: Unknown OS"
    get_os

    EXIT_CODE=1
fi
exit ${EXIT_CODE}
