# ----------------------------------------------------------------------

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."
alias ~="cd ~"
alias -- -="cd -"

# ----------------------------------------------------------------------

alias :q='exit'
alias ll='ls -lGha'
alias mv='mv -v'
alias rm='rm -v'
alias cp='cp -v'
alias less='less -r'
alias map='xargs -n1'

# ----------------------------------------------------------------------

## Colorize grep commands
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

## Colorize ls commands
alias ls='ls --color=auto'

# ----------------------------------------------------------------------

# Recursively delete `.DS_Store` files
alias cleanup_dsstore="find . -name '*.DS_Store' -type f -ls -delete"

# ----------------------------------------------------------------------

# Enable aliases to be sudo-ed
alias sudo='sudo '

# Get week number
alias week='date +%V'

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# ----------------------------------------------------------------------

# Source local aliases
[ -f ~/.bash_aliases.local ] && source ~/.bash_aliases.local
