#!/bin/bash

# Shell Variables
# http://linux.die.net/man/1/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make vim the default editor
export EDITOR='vim'

# Ignore commands that start with spaces and duplicates
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines of history
# persisted in the Bash history file (default value is 500)
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
# ---------------------
# HISTFILESIZE: number of lines in the history file
export HISTFILESIZE=
# HISTSIZE: the number of entries in the history file
export HISTSIZE=

# Don't add certain commands to the history file
export HISTIGNORE='&:[bf]g:c:clear:history:exit:q:pwd:* --help'

# Add timestamps
export HISTTIMEFORMAT='%Y-%m-%d %H:%M.%S | '

# Prefer US English and use UTF-8 encoding
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Use custom `less` colors for man pages
# https://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html
export LESS_TERMCAP_md=$'\e[1;32m'   # begin bold mode
export LESS_TERMCAP_me=$'\e[0m'      # end bold mode

# Don't clear the screen after quitting a man page
export MANPAGER="less -X"

# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Make Python use UTF-8 encoding for output to stdin/stdout/stderr
export PYTHONIOENCODING="UTF-8"

# Add RVM to PATH
export PATH="$PATH:$HOME/.rvm/bin"

# Add Android SDK
export ANDROID_HOME=/usr/local/opt/android-sdk

# Add nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Add go
export GOPATH="$HOME/go"
export PATH=$PATH:/usr/local/opt/go/libexec/bin

# VTE
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
fi

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

[ -f ~/.bash_exports.local ] && source ~/.bash_exports.local
